Run cargo with CARGO_HTTP_DEBUG=true
Without this environment variable set, the intitial configuration
fails with:

error: failed to get `platforms` as a dependency of package `corrosion-generator v0.1.0 (...)`

Caused by:
  failed to load source for dependency `platforms`

Caused by:
  Unable to update https://github.com/RustSec/platforms-crate.git?branch=master#dab5f2e6

Caused by:
  failed to fetch into: /local_home/frej/.cargo/git/db/platforms-crate-d65c8a3ec7bbf370

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  http parser did not consume entire buffer: success; class=Http (34)