Run `cargo test` with CARGO_HTTP_DEBUG=true
Without CARGO_HTTP_DEBUG=true cargo fails with:

 Updating crates.io index
warning: spurious network error (2 tries remaining): http parser did not consume entire buffer: success; class=Http (34)
warning: spurious network error (1 tries remaining): http parser did not consume entire buffer: success; class=Http (34)
error: failed to get `hexf` as a dependency of package `toplevel v0.1.0 (..)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  http parser did not consume entire buffer: success; class=Http (34)